In [1]:
import pandas as pd
#import psycopg2
from sqlalchemy import create_engine
from django.conf import settings

In [31]:
education_df = pd.read_csv(r'./World bank data/HNP_StatsData.csv')



# pruned_df = country_df[["Short Name", "Region", "Currency Unit", "WB-2 code", 'Country Code', 
#                 'Source of most recent Income and expenditure data', 'System of trade', 'External debt Reporting status', 'Lending category',
#                 'SNA price valuation', 'Income Group', 'Latest population census', 'Latest household survey']]

# education_df = pruned_df.loc[
#                 (pruned_df['Short Name'] == 'Canada') | (pruned_df['Short Name'] == 'United States') | 
#                 (pruned_df['Short Name'] == 'Mexico') | (pruned_df['Short Name'] == 'Mauritius') |
#                 (pruned_df['Short Name'] == 'Liberia') | (pruned_df['Short Name'] == 'Dem. Rep. Congo') |
#                 (pruned_df['Short Name'] == 'Vietnam') | (pruned_df['Short Name'] == 'Nepal') | 
#                 (pruned_df['Short Name'] == 'Bangladesh')]

education_dfCopy = education_df.copy()
education_dfCopy = education_dfCopy.rename(columns={'Country Name': 'CountryName'})
education_dfCopy  = education_dfCopy .drop(education_dfCopy [(education_dfCopy .CountryName != "Canada") &
                                                                      (education_dfCopy.CountryName != "United States") & 
                                                                      (education_dfCopy.CountryName != "Mexico") &
                                                                     (education_dfCopy.CountryName != "Mauritius") &
                                                                      (education_dfCopy.CountryName != "Liberia") &
                                                                      (education_dfCopy.CountryName != "Dem. Rep. Congo") &
                                                                      (education_dfCopy.CountryName != "Vietnam") &
                                                                      (education_dfCopy.CountryName != "Nepal") &
                                                                      (education_dfCopy.CountryName != "Bangladesh") 
                                                                      ].index)

education_dfCopy = education_dfCopy.rename(columns={'Indicator Name': 'Indicator_Name'})
education_dfCopy  = education_dfCopy .drop(education_dfCopy [(education_dfCopy.Indicator_Name != "Literacy rate, adult female (% of females ages 15 and above)") &
                                                                      (education_dfCopy.Indicator_Name != "Literacy rate, adult male (% of males ages 15 and above)") & 
                                                                      (education_dfCopy.Indicator_Name != "Literacy rate, adult total (% of people ages 15 and above)") &
                                                                     (education_dfCopy.Indicator_Name != "Literacy rate, youth total (% of people ages 15-24)") &
                                                                      (education_dfCopy.Indicator_Name != "Public spending on education, total (% of GDP)") &
                                                                      (education_dfCopy.Indicator_Name != "School enrollment, primary, male (% gross)") &
                                                                      (education_dfCopy.Indicator_Name != "School enrollment, primary, female (% gross)") &
                                                                      (education_dfCopy.Indicator_Name != "School enrollment, secondary, male (% gross)") &
                                                                      (education_dfCopy.Indicator_Name != "School enrollment, secondary, female (% gross)") &
                                                                      (education_dfCopy.Indicator_Name != "School enrollment, tertiary, female (% gross)") &
                                                                      (education_dfCopy.Indicator_Name != "School enrollment, tertiary (% gross)") &
                                                                      (education_dfCopy.Indicator_Name != "Primary completion rate, total (% of relevant age group)") 
                                                                      ].index)
education_dfCopy = education_dfCopy.drop(['1960', '1961', '1962', '1963', '1964',
       '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973',
       '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982',
       '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', 'Country Code', 'Indicator Code', 'Unnamed: 66', '2021'], axis=1)
#education_dfCopy =pd.pivot_table(education_dfCopy,index=["Indicator_Name"])
education_dfCopy.set_index('Indicator_Name',inplace=True)
education_dfCopy1 = education_dfCopy[["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020"]]
print((education_dfCopy1.T).columns)

Index(['Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, adult male (% of males ages 15 and above)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Literacy rate, youth total (% of people ages 15-24)',
       'Primary completion rate, total (% of relevant age group)',
       'Public spending on education, total (% of GDP)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, male (% gross)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, male (% gross)',
       'School enrollment, tertiary (% gross)',
       'School enrollment, tertiary, female (% gross)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, adult male (% of males ages 15 and above)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Literacy rate, youth total (% of people ages 15-24)',
       'Primary completion rate, total (% of relevant age group)',
       'Public spending on education, total (% of GDP)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, male (% gross)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, male (% gross)',
       'School enrollment, tertiary (% gross)',
       'School enrollment, tertiary, female (% gross)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, adult male (% of males ages 15 and above)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Literacy rate, youth total (% of people ages 15-24)',
       'Primary completion rate, total (% of relevant age group)',
       'Public spending on education, total (% of GDP)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, male (% gross)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, male (% gross)',
       'School enrollment, tertiary (% gross)',
       'School enrollment, tertiary, female (% gross)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, adult male (% of males ages 15 and above)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Literacy rate, youth total (% of people ages 15-24)',
       'Primary completion rate, total (% of relevant age group)',
       'Public spending on education, total (% of GDP)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, male (% gross)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, male (% gross)',
       'School enrollment, tertiary (% gross)',
       'School enrollment, tertiary, female (% gross)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, adult male (% of males ages 15 and above)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Literacy rate, youth total (% of people ages 15-24)',
       'Primary completion rate, total (% of relevant age group)',
       'Public spending on education, total (% of GDP)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, male (% gross)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, male (% gross)',
       'School enrollment, tertiary (% gross)',
       'School enrollment, tertiary, female (% gross)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, adult male (% of males ages 15 and above)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Literacy rate, youth total (% of people ages 15-24)',
       'Primary completion rate, total (% of relevant age group)',
       'Public spending on education, total (% of GDP)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, male (% gross)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, male (% gross)',
       'School enrollment, tertiary (% gross)',
       'School enrollment, tertiary, female (% gross)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, adult male (% of males ages 15 and above)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Literacy rate, youth total (% of people ages 15-24)',
       'Primary completion rate, total (% of relevant age group)',
       'Public spending on education, total (% of GDP)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, male (% gross)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, male (% gross)',
       'School enrollment, tertiary (% gross)',
       'School enrollment, tertiary, female (% gross)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, adult male (% of males ages 15 and above)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Literacy rate, youth total (% of people ages 15-24)',
       'Primary completion rate, total (% of relevant age group)',
       'Public spending on education, total (% of GDP)',
       'School enrollment, primary, female (% gross)',
       'School enrollment, primary, male (% gross)',
       'School enrollment, secondary, female (% gross)',
       'School enrollment, secondary, male (% gross)',
       'School enrollment, tertiary (% gross)',
       'School enrollment, tertiary, female (% gross)'],
      dtype='object', name='Indicator_Name')

In [3]:
column_map = {
                "Short Name" : "Name",
                "Region" : "Region"
            }

capital_map = { "Canada" : "Ottawa",
                "United States" : "Washington DC",
                "Mexico" : "Mexico City",
                "Mauritius" : "Port Louis",
                "Liberia" : "Monrovia",
                "Dem. Rep. Congo" : "Kinshasa",
                "Vietnam" : "Hanoi", 
                "Nepal" : "kathmandu",
                "Bangladesh" : "Dhaka"}

continent_map = { "Canada" : "North America",
                "United States" : "North America",
                "Mexico" : "North America",
                "Mauritius" : "Africa",
                "Liberia" : "Africa",
                "Dem. Rep. Congo" : "Africa",
                "Vietnam" : "Asia", 
                "Nepal" : "Asia",
                "Bangladesh" : "Asia"}

In [4]:
engine = create_engine('postgresql://scott:tiger@localhost/mydatabase')

ModuleNotFoundError: No module named 'psycopg2'

In [ ]:
for item in capital_map: